### ISSUE TITLE
Crash on start [SQLiteConstraintException]

### ISSUE THREAD

**Issue by dgarkov** [BeniEnge/as_son_of_hunkypunk#56]
The app crashes occasionally when started. _It is caused by a constraint in the database. The game *Plant_ and its ID are what actually causes the exception.  The error is more precisely:*

```
07-24 09:14:39.670 2319-2423/org.andglk.hunkypunk E/SQLiteDatabase: Error inserting path=/storage/sdcard/Interactive Fiction/plant.gam title=plant ifid=TADS2-A94AFB10D704EF53BA57E9DE95B49422
                                                                android.database.sqlite.SQLiteConstraintException: column ifid is not unique (code 19)
                                                                    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
                                                                    at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
                                                                    at org.andglk.hunkypunk.HunkyPunkProvider.insert(HunkyPunkProvider.java:104)
                                                                    at android.content.ContentProvider$Transport.insert(ContentProvider.java:220)
                                                                    at android.content.ContentResolver.insert(ContentResolver.java:1190)
                                                                    at org.andglk.hunkypunk.StorageManager.checkFile(StorageManager.java:208)
                                                                    at org.andglk.hunkypunk.StorageManager.checkFile(StorageManager.java:192)
                                                                    at org.andglk.hunkypunk.StorageManager.scan(StorageManager.java:148)
                                                                    at org.andglk.hunkypunk.StorageManager$2.run(StorageManager.java:238)
07-24 09:14:39.670 2319-2423/org.andglk.hunkypunk W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0xa4d59b20)
07-24 09:14:39.670 2319-2423/org.andglk.hunkypunk E/AndroidRuntime: FATAL EXCEPTION: Thread-85
                                                                Process: org.andglk.hunkypunk, PID: 2319
                                                                android.database.SQLException: Failed to insert row into content://org.andglk.hunkypunk.HunkyPunk/games
                                                                    at org.andglk.hunkypunk.HunkyPunkProvider.insert(HunkyPunkProvider.java:111)
                                                                    at android.content.ContentProvider$Transport.insert(ContentProvider.java:220)
                                                                    at android.content.ContentResolver.insert(ContentResolver.java:1190)
                                                                    at org.andglk.hunkypunk.StorageManager.checkFile(StorageManager.java:208)
                                                                    at org.andglk.hunkypunk.StorageManager.checkFile(StorageManager.java:192)
                                                                    at org.andglk.hunkypunk.StorageManager.scan(StorageManager.java:148)
                                                                    at org.andglk.hunkypunk.StorageManager$2.run(StorageManager.java:238)
```

Actually the real cause is a refresh of the GamesList which violates the database and subsequently crashes the app.

**Comment by dgarkov** [comment]
fixed see [this](https://github.com/BeniEnge/as_son_of_hunkypunk/commit/559f0cff0a569f270dc9849ff30d032530f08e0c).
